import { createTheme } from '@mui/material/styles';
import type { SxProps, Theme } from '@mui/material/styles';

export const uiColors = {
  bg: {
    base: '#081427',
    surface: '#10213a',
    sidebar: 'rgba(9, 24, 45, 0.88)',
    overlay: 'rgba(10, 24, 44, 0.96)',
    boardPanel: 'rgba(10, 28, 52, 0.9)',
  },
  text: {
    primary: '#f4f8ff',
    secondary: '#c4d7f4',
    muted: '#9fb5d8',
  },
  accent: {
    main: '#59c3ff',
    light: '#90dbff',
    dark: '#2699d6',
    hoverBg: 'rgba(89, 195, 255, 0.18)',
  },
  border: {
    strong: 'rgba(154, 198, 255, 0.36)',
    soft: 'rgba(154, 198, 255, 0.22)',
    faint: 'rgba(154, 198, 255, 0.14)',
  },
  feedback: {
    error: '#ff6b6b',
  },
  board: {
    empty: '#ede4d3',
    human: '#62d986',
    opponent: '#ff7d7d',
  },
} as const;

const theme = createTheme({
  typography: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  },
  palette: {
    mode: 'dark',
    primary: {
      main: uiColors.accent.main,
      light: uiColors.accent.light,
      dark: uiColors.accent.dark,
      contrastText: '#042033',
    },
    error: {
      main: uiColors.feedback.error,
    },
    background: {
      default: uiColors.bg.base,
      paper: uiColors.bg.surface,
    },
    text: {
      primary: uiColors.text.primary,
      secondary: uiColors.text.secondary,
    },
  },
  shape: {
    borderRadius: 10,
  },
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        body: {
          margin: 0,
          minWidth: 320,
          minHeight: '100vh',
          fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        },
        '#root': {
          width: '100%',
        },
      },
    },
    MuiButton: {
      defaultProps: {
        disableElevation: true,
        variant: 'contained',
        size: 'medium',
      },
      styleOverrides: {
        root: {
          fontWeight: 700,
          textTransform: 'none',
          minWidth: 148,
          height: 40,
          borderRadius: 10,
          whiteSpace: 'nowrap',
        },
        containedPrimary: {
          color: '#042033',
          '&:hover': {
            backgroundColor: uiColors.accent.light,
          },
        },
        outlined: {
          borderColor: uiColors.border.strong,
          color: uiColors.text.primary,
          '&:hover': {
            borderColor: uiColors.accent.light,
            backgroundColor: uiColors.accent.hoverBg,
          },
        },
        text: {
          color: uiColors.accent.light,
          '&:hover': {
            color: uiColors.text.primary,
            backgroundColor: uiColors.accent.hoverBg,
          },
        },
      },
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          border: `1px solid ${uiColors.border.soft}`,
        },
      },
    },
    MuiTabs: {
      styleOverrides: {
        indicator: {
          backgroundColor: uiColors.accent.light,
          height: 3,
          borderRadius: 3,
        },
      },
    },
    MuiTab: {
      styleOverrides: {
        root: {
          color: uiColors.text.secondary,
          fontWeight: 700,
          '&.Mui-selected': {
            color: uiColors.accent.light,
          },
          '&:hover': {
            color: uiColors.text.primary,
            backgroundColor: uiColors.accent.hoverBg,
          },
        },
      },
    },
    MuiFilledInput: {
      styleOverrides: {
        root: {
          backgroundColor: 'rgba(255, 255, 255, 0.08)',
          '&:hover': {
            backgroundColor: 'rgba(255, 255, 255, 0.12)',
          },
          '&.Mui-focused': {
            backgroundColor: 'rgba(255, 255, 255, 0.12)',
            boxShadow: `0 0 0 1px ${uiColors.accent.light}`,
          },
          '&:before, &:after': {
            display: 'none',
          },
        },
        input: {
          color: uiColors.text.primary,
        },
      },
    },
    MuiInputLabel: {
      styleOverrides: {
        root: {
          color: uiColors.text.secondary,
          '&.Mui-focused': {
            color: uiColors.accent.light,
          },
        },
      },
    },
    MuiTextField: {
      defaultProps: {
        variant: 'filled',
        size: 'small',
      },
    },
  },
});

export const uiSx = {
  appShell: {
    width: '100%',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    px: { xs: 1.2, md: 1.8 },
    py: { xs: 1, md: 1.3 },
    gap: 1.5,
  } satisfies SxProps<Theme>,
  appHeader: {
    width: '100%',
    borderBottom: `1px solid ${uiColors.border.soft}`,
    border: `1px solid ${uiColors.border.faint}`,
    borderRadius: 2.2,
    backgroundColor: 'rgba(16, 33, 58, 0.72)',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.2)',
    py: 1.9,
    px: 2.2,
  } satisfies SxProps<Theme>,
  appHeaderTitle: {
    textAlign: 'center',
    fontWeight: 800,
    letterSpacing: 1,
    fontSize: { xs: '1.9rem', sm: '2.3rem' },
  } satisfies SxProps<Theme>,
  appHeaderUserRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 2,
    flexWrap: 'wrap',
  } satisfies SxProps<Theme>,
  appHeaderTitleSecondary: {
    textAlign: 'left',
    fontWeight: 800,
    letterSpacing: 1,
    fontSize: { xs: '1.6rem', sm: '2rem' },
    lineHeight: 1.2,
  } satisfies SxProps<Theme>,
  appHeaderTitleLink: {
    border: 'none',
    background: 'transparent',
    color: 'inherit',
    padding: 0,
    margin: 0,
    textAlign: 'left',
    fontWeight: 800,
    letterSpacing: 1,
    fontSize: { xs: '1.6rem', sm: '2rem' },
    lineHeight: 1.2,
    cursor: 'pointer',
    fontFamily: 'inherit',
  } satisfies SxProps<Theme>,
  appHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    ml: 'auto',
  } satisfies SxProps<Theme>,
  appHeaderUserBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.7,
    px: 1.1,
    py: 0.45,
    borderRadius: 1.2,
    border: `1px solid ${uiColors.border.soft}`,
    backgroundColor: 'rgba(89, 195, 255, 0.06)',
  } satisfies SxProps<Theme>,
  appHeaderUserText: {
    fontSize: '0.92rem',
    letterSpacing: 0.2,
    color: 'text.secondary',
    lineHeight: 1.2,
  } satisfies SxProps<Theme>,
  appHeaderUserName: {
    fontWeight: 800,
    color: 'text.primary',
    letterSpacing: 0.25,
  } satisfies SxProps<Theme>,
  appRoot: {
    width: '100%',
    maxWidth: 920,
    px: 2,
    py: 4,
    mx: 'auto',
  } satisfies SxProps<Theme>,
  appBody: {
    display: 'flex',
    alignItems: 'stretch',
    width: '100%',
    flex: 1,
    minHeight: 0,
    flexDirection: { xs: 'column', md: 'row' },
    gap: 2,
    pb: 0.6,
  } satisfies SxProps<Theme>,
  appMain: {
    flex: 1,
    width: '100%',
    px: { xs: 2.1, md: 3.4 },
    py: { xs: 2.2, md: 2.8 },
    minWidth: 0,
    maxWidth: 'none',
  } satisfies SxProps<Theme>,
  sidebar: {
    width: { xs: '100%', md: 206 },
    flexShrink: 0,
    px: 2,
    py: 2.5,
    borderRight: { xs: 'none', md: `1px solid ${uiColors.border.faint}` },
    borderBottom: { xs: `1px solid ${uiColors.border.faint}`, md: 'none' },
    backgroundColor: uiColors.bg.sidebar,
    borderRadius: 2.2,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    position: 'relative',
    overflow: 'visible',
  } satisfies SxProps<Theme>,
  sidebarPlayGroup: {
    position: 'relative',
    width: '100%',
  } satisfies SxProps<Theme>,
  sidebarItem: (active: boolean): SxProps<Theme> => ({
    border: 'none',
    background: 'transparent',
    color: active ? uiColors.accent.light : 'inherit',
    textAlign: 'left',
    padding: '9px 12px',
    borderRadius: 10,
    fontWeight: 600,
    fontSize: '0.98rem',
    width: '100%',
    minWidth: '100%',
    height: 'auto',
    cursor: 'pointer',
    display: 'block',
    transition: 'background-color 0.18s ease, color 0.18s ease',
    '&:hover': {
      color: uiColors.accent.light,
      backgroundColor: uiColors.accent.hoverBg,
    },
  }),
  sidebarItemContent: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
  } satisfies SxProps<Theme>,
  sidebarItemIcon: {
    width: 20,
    height: 20,
    display: 'block',
    objectFit: 'contain',
    flexShrink: 0,
  } satisfies SxProps<Theme>,
  sidebarSubmenu: (open: boolean): SxProps<Theme> => ({
    position: { xs: 'static', md: 'absolute' },
    left: { md: '100%' },
    top: { md: 0 },
    mt: { xs: 1, md: 0 },
    minWidth: 220,
    display: open ? 'flex' : 'none',
    flexDirection: 'column',
    gap: 0.3,
    p: 1.1,
    borderRadius: 2,
    border: `1px solid ${uiColors.border.soft}`,
    backgroundColor: uiColors.bg.overlay,
    boxShadow: '0 10px 26px rgba(0, 0, 0, 0.35)',
    zIndex: 3,
  }),
  sidebarSubmenuDivider: {
    mt: 0.7,
    mb: 0.5,
    mx: 0.4,
    borderTop: `1px solid ${uiColors.border.soft}`,
  } satisfies SxProps<Theme>,
  sidebarSubmenuTitle: {
    px: 1,
    py: 0.5,
    fontSize: '0.8rem',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: 'text.secondary',
    opacity: 0.9,
  } satisfies SxProps<Theme>,
  sidebarOption: {
    border: 'none',
    background: 'transparent',
    color: 'inherit',
    textAlign: 'left',
    padding: '8px 10px',
    borderRadius: 8,
    fontSize: '0.94rem',
    cursor: 'pointer',
    width: '100%',
    minWidth: '100%',
    height: 'auto',
    display: 'block',
    transition: 'background-color 0.16s ease, color 0.16s ease',
    '&:hover': {
      color: uiColors.accent.light,
      backgroundColor: uiColors.accent.hoverBg,
    },
  } satisfies SxProps<Theme>,
  sidebarOptionDisabled: {
    px: 1,
    py: 0.75,
    borderRadius: 1,
    fontSize: '0.94rem',
    color: 'text.secondary',
    opacity: 0.55,
  } satisfies SxProps<Theme>,
  sidebarBottom: {
    mt: 'auto',
    pt: 1.5,
  } satisfies SxProps<Theme>,
  dashboardShell: {
    width: '100%',
    maxWidth: 1160,
    mx: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 2.4,
  } satisfies SxProps<Theme>,
  dashboardTopRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', lg: '1fr 1fr' },
    gap: 2.3,
    alignItems: 'stretch',
  } satisfies SxProps<Theme>,
  dashboardCard: {
    p: 2.4,
    borderRadius: 2,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.25,
    minHeight: 252,
    height: '100%',
  } satisfies SxProps<Theme>,
  dashboardCardTitle: {
    position: 'relative',
    display: 'inline-flex',
    width: 'fit-content',
    alignItems: 'center',
    gap: 0.7,
    pr: 0.8,
    pb: 0.85,
    fontWeight: 800,
    letterSpacing: 0.35,
    textShadow: '0 1px 0 rgba(0, 0, 0, 0.18)',
    '&::before': {
      content: '""',
      width: 7,
      height: 7,
      borderRadius: '50%',
      backgroundColor: uiColors.accent.light,
      boxShadow: `0 0 10px ${uiColors.accent.light}`,
      opacity: 0.85,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 2,
      borderRadius: 2,
      background: `linear-gradient(90deg, ${uiColors.accent.light} 0%, rgba(255,255,255,0) 92%)`,
    },
  } satisfies SxProps<Theme>,
  dashboardCardHint: {
    color: 'text.secondary',
    fontSize: '0.9rem',
  } satisfies SxProps<Theme>,
  dashboardInlineHint: {
    mt: 1.1,
    color: 'text.secondary',
    fontSize: '0.82rem',
    letterSpacing: 0.15,
  } satisfies SxProps<Theme>,
  configSectionTitle: {
    fontSize: '0.76rem',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: 'text.secondary',
    fontWeight: 700,
  } satisfies SxProps<Theme>,
  configToggleButton: (active: boolean): SxProps<Theme> => ({
    minWidth: { xs: '100%', sm: 108 },
    height: 34,
    px: 1.4,
    borderRadius: 1.4,
    fontSize: '0.88rem',
    fontWeight: 700,
    color: active ? 'text.primary' : 'text.secondary',
    backgroundColor: active ? 'rgba(255, 255, 255, 0.15)' : 'rgba(255, 255, 255, 0.08)',
    borderColor: active ? 'primary.light' : 'divider',
    '&:hover': {
      backgroundColor: active ? 'rgba(255, 255, 255, 0.2)' : 'rgba(255, 255, 255, 0.12)',
      borderColor: active ? 'primary.light' : 'primary.main',
    },
  }),
  configGrid: {
    mt: 0.9,
    display: 'grid',
    gap: 1.35,
  } satisfies SxProps<Theme>,
  configRow: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '112px 1fr' },
    gap: 1.1,
    alignItems: 'center',
  } satisfies SxProps<Theme>,
  configRowStart: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '112px 1fr' },
    gap: 1.1,
    alignItems: 'start',
  } satisfies SxProps<Theme>,
  configRowDivider: {
    borderTop: '1px solid',
    borderColor: 'divider',
    opacity: 0.45,
    my: 0.4,
  } satisfies SxProps<Theme>,
  configOptionGroup: {
    display: 'flex',
    flexWrap: { xs: 'wrap', sm: 'nowrap' },
    gap: 1,
  } satisfies SxProps<Theme>,
  configSizeInput: {
    width: { xs: '100%', sm: 220 },
  } satisfies SxProps<Theme>,
  configActions: {
    mt: 'auto',
    pt: 0.8,
    display: 'flex',
    justifyContent: 'flex-end',
  } satisfies SxProps<Theme>,
  dashboardConfigControls: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1.5,
    alignItems: 'center',
    mt: 'auto',
  } satisfies SxProps<Theme>,
  statsRows: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    mt: 0.5,
  } satisfies SxProps<Theme>,
  statsRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    px: 1.2,
    py: 0.9,
    borderRadius: 1.4,
    border: `1px solid ${uiColors.border.faint}`,
    backgroundColor: 'rgba(10, 28, 52, 0.62)',
  } satisfies SxProps<Theme>,
  dashboardHistoryCard: {
    p: 2.4,
    borderRadius: 2,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.2,
  } satisfies SxProps<Theme>,
  historyFooter: {
    display: 'flex',
    justifyContent: 'flex-end',
    pt: 1,
  } satisfies SxProps<Theme>,
  historyFullscreenCard: {
    p: 2.4,
    borderRadius: 2,
    width: '100%',
    minHeight: 520,
    display: 'flex',
    flexDirection: 'column',
    gap: 1.6,
  } satisfies SxProps<Theme>,
  historyHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 1.5,
    flexWrap: 'wrap',
  } satisfies SxProps<Theme>,
  appTitle: {
    mb: 2,
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  errorText: {
    mb: 2,
    textAlign: 'center',
  } satisfies SxProps<Theme>,
  centeredColumn: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    alignItems: 'center',
  } satisfies SxProps<Theme>,
  panel: (maxWidth: number): SxProps<Theme> => ({
    p: 3,
    width: '100%',
    maxWidth,
  }),
  centeredRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: 1,
  } satisfies SxProps<Theme>,
  formColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    width: '100%',
    maxWidth: 360,
    mx: 'auto',
  } satisfies SxProps<Theme>,
  loginTitle: {
    fontWeight: 800,
    letterSpacing: 0.5,
    fontSize: { xs: '1.6rem', sm: '1.95rem' },
    textAlign: 'center',
    color: 'text.primary',
    textShadow: '0 2px 12px rgba(0, 0, 0, 0.25)',
  } satisfies SxProps<Theme>,
  authTabs: {
    mb: 2,
    border: `1px solid ${uiColors.border.faint}`,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    overflow: 'hidden',
  } satisfies SxProps<Theme>,
  boardContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    mt: 2,
  } satisfies SxProps<Theme>,
  gameBoardStage: {
    position: 'relative',
    width: 'fit-content',
    mx: 'auto',
    mt: 1,
    mb: 3,
    px: 5.8,
    pt: 4.4,
    pb: 3.4,
    transform: 'translateX(6px)',
    isolation: 'isolate',
  } satisfies SxProps<Theme>,
  gameBoardBase: {
    position: 'absolute',
    zIndex: -1,
    inset: '-4px -8px -1px -7px',
    clipPath: 'polygon(46% 7%, 54% 7%, 96% 92%, 92% 100%, 7% 100%, 4% 92%)',
    backgroundColor: uiColors.bg.boardPanel,
    boxShadow: '0 10px 20px rgba(0, 0, 0, 0.25)',
  } satisfies SxProps<Theme>,
  gameActionsBox: {
    width: 'fit-content',
    mx: 'auto',
    p: 1.5,
    borderRadius: 2,
    border: `1px solid ${uiColors.border.faint}`,
    backgroundColor: uiColors.bg.boardPanel,
    boxShadow: '0 10px 20px rgba(0, 0, 0, 0.25)',
  } satisfies SxProps<Theme>,
  boardRow: (size: number, rowIndex: number): SxProps<Theme> => ({
    display: 'flex',
    justifyContent: 'center',
    mb: '-14px',
    ml: `${size - (rowIndex + 1)}px`,
  }),
  boardHex: (color: string, clickable: boolean): SxProps<Theme> => ({
    width: 48,
    height: 56,
    backgroundColor: color,
    margin: '4px',
    clipPath: `polygon(
      50% 0%,
      100% 25%,
      100% 75%,
      50% 100%,
      0% 75%,
      0% 25%
    )`,
    transition: '0.12s',
    display: 'inline-block',
    '&:hover': clickable ? { filter: 'brightness(0.92)', cursor: 'pointer' } : {},
  }),
};

export default theme;




