services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - monitor-net

  stats:
    build: ./stats
    container_name: stats
    image: ghcr.io/arquisoft/yovi_es4b-stats:latest
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=yovi_stats
      - STATS_INTERNAL_TOKEN=stats-internal-token
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    container_name: gateway
    image: ghcr.io/arquisoft/yovi_es4b-gateway:latest
    ports:
      - "80:8080"
    depends_on:
      - webapp
      - users
      - gamey
      - stats
    networks:
      - monitor-net

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es4b-users:latest
    networks:
      - monitor-net

  webapp:
    build: ./webapp
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es4b-webapp:latest
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es4b-gamey:latest
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mongo-data:
