sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es4b
sonar.projectName=yovi_es4b

sonar.sources=webapp/src,users,gateway,stats,gamey/src
sonar.tests=webapp/src,users/__tests__,gateway,stats,gamey/tests
sonar.test.inclusions=**/*.test.tsx,**/*.test.js,**/*_tests.rs
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info,gateway/coverage/lcov.info,stats/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info
