'use strict';

const PROMETHEUS_CONTENT_TYPE = 'text/plain; version=0.0.4; charset=utf-8';

function createPrometheusMetrics({ serviceName }) {
  if (!serviceName || typeof serviceName !== 'string') {
    throw new Error('serviceName is required to create Prometheus metrics');
  }

  const requestMetrics = new Map();

  function middleware(req, res, next) {
    const route = normalizePath(req.originalUrl ?? req.url);
    if (route === '/metrics') {
      next();
      return;
    }

    const startedAt = process.hrtime.bigint();

    res.on('finish', () => {
      const durationSeconds = Number(process.hrtime.bigint() - startedAt) / 1e9;
      const key = buildMetricKey(req.method ?? 'GET', route, String(res.statusCode));
      const entry = requestMetrics.get(key) ?? {
        method: req.method ?? 'GET',
        route,
        status: String(res.statusCode),
        count: 0,
        durationSumSeconds: 0,
      };

      entry.count += 1;
      entry.durationSumSeconds += durationSeconds;
      requestMetrics.set(key, entry);
    });

    next();
  }

  function handler(_req, res) {
    res.set('Content-Type', PROMETHEUS_CONTENT_TYPE);
    res.send(renderMetrics());
  }

  function reset() {
    requestMetrics.clear();
  }

  function renderMetrics() {
    const memoryUsage = process.memoryUsage();
    const lines = [];

    appendMetadata(lines);
    appendGauge(lines, 'yovi_process_uptime_seconds', 'Process uptime in seconds', [
      {
        labels: { service: serviceName },
        value: process.uptime(),
      },
    ]);
    appendGauge(lines, 'yovi_process_resident_memory_bytes', 'Resident memory size in bytes', [
      {
        labels: { service: serviceName },
        value: memoryUsage.rss,
      },
    ]);
    appendGauge(lines, 'yovi_process_heap_used_bytes', 'Used V8 heap in bytes', [
      {
        labels: { service: serviceName },
        value: memoryUsage.heapUsed,
      },
    ]);

    const entries = [...requestMetrics.values()].sort(compareRequestMetrics);

    appendCounter(lines, 'yovi_http_requests_total', 'HTTP requests handled by the service', entries.map((entry) => ({
      labels: {
        service: serviceName,
        method: entry.method,
        route: entry.route,
        status: entry.status,
      },
      value: entry.count,
    })));
    appendCounter(
      lines,
      'yovi_http_request_duration_seconds_sum',
      'Total HTTP request duration in seconds',
      entries.map((entry) => ({
        labels: {
          service: serviceName,
          method: entry.method,
          route: entry.route,
          status: entry.status,
        },
        value: entry.durationSumSeconds,
      })),
    );
    appendCounter(
      lines,
      'yovi_http_request_duration_seconds_count',
      'Number of HTTP requests observed for duration aggregation',
      entries.map((entry) => ({
        labels: {
          service: serviceName,
          method: entry.method,
          route: entry.route,
          status: entry.status,
        },
        value: entry.count,
      })),
    );

    return `${lines.join('\n')}\n`;
  }

  return {
    handler,
    middleware,
    reset,
    renderMetrics,
  };
}

function buildMetricKey(method, route, status) {
  return `${method} ${route} ${status}`;
}

function normalizePath(rawUrl = '/') {
  const parsedUrl = new URL(rawUrl, 'http://localhost');
  const pathSegments = parsedUrl.pathname
    .split('/')
    .filter(Boolean)
    .map(normalizeSegment);

  return pathSegments.length === 0 ? '/' : `/${pathSegments.join('/')}`;
}

function normalizeSegment(segment) {
  if (/^\d+$/.test(segment)) {
    return ':id';
  }

  if (/^(game|ticket|ptk)-[a-z0-9-]+$/i.test(segment)) {
    return ':id';
  }

  if (/^[0-9a-f]{8,}$/i.test(segment) || /^[0-9a-f-]{8,}$/i.test(segment)) {
    return ':id';
  }

  return segment;
}

function compareRequestMetrics(left, right) {
  return (
    left.route.localeCompare(right.route) ||
    left.method.localeCompare(right.method) ||
    left.status.localeCompare(right.status)
  );
}

function appendMetadata(lines) {
  lines.push('# Generated by Yovi Prometheus metrics helper');
}

function appendGauge(lines, name, help, samples) {
  appendMetric(lines, name, help, 'gauge', samples);
}

function appendCounter(lines, name, help, samples) {
  appendMetric(lines, name, help, 'counter', samples);
}

function appendMetric(lines, name, help, type, samples) {
  lines.push(`# HELP ${name} ${help}`, `# TYPE ${name} ${type}`);

  for (const sample of samples) {
    lines.push(`${name}${formatLabels(sample.labels)} ${sample.value}`);
  }
}

function formatLabels(labels) {
  const pairs = Object.entries(labels ?? {});
  if (pairs.length === 0) {
    return '';
  }

  const rendered = pairs
    .map(([key, value]) => `${key}="${escapeLabelValue(value)}"`)
    .join(',');

  return `{${rendered}}`;
}

function escapeLabelValue(value) {
  return String(value)
    .replaceAll('\\', String.raw`\\`)
    .replaceAll('\n', String.raw`\n`)
    .replaceAll('"', String.raw`\"`);
}

module.exports = {
  createPrometheusMetrics,
};
